Refactoring: Extract generic dumpMozillaAddons from dump-Firefox-addons

diff --git a/bin/dump-Firefox-addons b/bin/dump-Firefox-addons
--- a/bin/dump-Firefox-addons
+++ b/bin/dump-Firefox-addons
@@ -1,32 +1,11 @@
 #!/bin/bash
-shopt -qs nullglob
 
-printUsage()
-{
-    cat <<HELPTEXT
-Print setup-software definitions for all Firefox add-ons installed under
-PROFILE-NAME / in all profiles.
-HELPTEXT
-    echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[PROFILE-NAME] [-?|-h|--help]'
-}
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-esac
+scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }
+projectDir="${scriptDir}/.."
 
+DUMPMOZILLAADDONS_SUBJECT=Firefox
+DUMPMOZILLAADDONS_PROFILES_DIRSPEC=~/.mozilla/firefox
+DUMPMOZILLAADDONS_SUBJECT_PACKAGE_NAME=firefox
 
-readonly FIREFOX_PROFILES_DIRSPEC=~/.mozilla/firefox
-addonsConfigFilespecs=("$FIREFOX_PROFILES_DIRSPEC"/*.${1:-*}/addons.json)
-if [ ${#addonsConfigFilespecs[@]} -eq 0 ]; then
-    echo >&2 "ERROR: No ${1:+such }Firefox profile found."
-    exit 3
-fi
-
-for addonsConfigFilespec in "${addonsConfigFilespecs[@]}"
-do
-    addonsConfigDirspec="$(dirname -- "$addonsConfigFilespec")"
-    profileName="${addonsConfigDirspec##*.}"
-    [[ "$profileName" =~ ^default(-release)?$ ]] && profileName=''
-
-    jq --raw-output ".addons | .[] | \"firefox:${profileName}:\\(.id):\\(.reviewURL|rtrimstr(\"reviews/\")) # \\(.name)\"" "$addonsConfigFilespec"
-done
+source "${projectDir}/lib/dumpMozillaAddons"
