setup-software: ENH: Allow direct execution of install commands via -e|--execute

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -14,9 +14,13 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-v|--verbose] [-y|--yes] [-s|--select DEFINITION [-s ...]] [--base-dir BASE-DIR] -a|--all|GROUP-NAME|GROUP-FILESPEC [...] [-?|-h|--help]|[-H|--config-help [TYPE]]'
+    printf 'Usage: %q %s | tee install-script.sh && sh install-script.sh\n' "$(basename "$1")" '[-v|--verbose] [-y|--yes] [-s|--select DEFINITION [-s ...]] [--base-dir BASE-DIR] -a|--all|GROUP-NAME|GROUP-FILESPEC [...] [-?|-h|--help]|[-H|--config-help [TYPE]]'
     echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-e|--execute [...]'
+    echo
+    echo '(For automation in a script:)'
     printf 'Usage: packageInstallCommandLine="$(%q %s)" && eval "$packageInstallCommandLine"\n' "$(basename "$1")" '--yes [--select DEFINITION] (--base-dir BASE-DIR -a|--all|GROUP-NAME | GROUP-FILESPEC)'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '--execute --yes [--select DEFINITION] (--base-dir BASE-DIR -a|--all|GROUP-NAME | GROUP-FILESPEC)'
 }
 printUsage()
 {
@@ -40,6 +44,9 @@ HELPDESCRIPTION
     --config-help|-H [TYPE]
 			Show details about the configuration syntax for all /
 			for TYPE.
+    --execute|-e	Directly execute the installation commands (as long as
+			they succeed; like with set -e) instead of just printing
+			them.
     --verbose|-v	Also mention already installed definitions that are
 			skipped.
     --yes|-y		Accept all definitions (that are not yet installed and
@@ -471,7 +478,15 @@ generateInstallCommands()
 printInstallCommands()
 {
     [ ${#toBeInstalledCommands[@]} -eq 0 ] && return 1
-    printf '%s\n' "${toBeInstalledCommands[@]}"
+
+    if [ "$isExecute" ]; then
+	local installCommandline="$(joinBy '; ' "${toBeInstalledCommands[@]}")"
+	set -e
+	eval "$installCommandline"
+	exit $?	# Exit the script now because else installation failure would be treated as if there were no installation commands.
+    else
+	printf '%s\n' "${toBeInstalledCommands[@]}"
+    fi
 }
 
 
@@ -479,6 +494,7 @@ obtainSelection=askTo
 isAddAll=
 typeset -a selections=()
 typeset -a specialHandlingCommands=()
+isExecute=
 isVerbose=
 typeset -a recursiveArgs=()
 while [ $# -ne 0 ]
@@ -492,6 +508,7 @@ do
 			exit 0
 			;;
 	--base-dir)	recursiveArgs+=("$1" "$2"); shift; baseDir="${1:?}"; shift;;
+	--execute|-e)	recursiveArgs+=("$1"); shift; isExecute=t;;
 	--verbose|-v)	recursiveArgs+=("$1"); shift; isVerbose=t;;
 	--yes|-y)	shift; obtainSelection=true;;
 	--select|-s)	shift; selections+=("$1"); shift;;
