setup-software: BUG: update-software only says that "definitions would be installed"
When a type of the to-be-installed items needs a prerequisite installed via isAvailableOrUserAccepts{Group,Native}(), but there's no answer to recall, this results in failure, but nothing is printed and there are no install commands, but we have a non-zero addedDefinitionCount.
Check for success of addItems() and print an error if that fails.

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -754,7 +754,8 @@ parseDefinitionGroups()
 		let addedDefinitionCount+=1
 		# Add the configurations first, so that they are available to the
 		# add*() function for the real item already.
-		addItems "${missingItemConfigurations[@]}" "${missingItems[@]}"
+		addItems "${missingItemConfigurations[@]}" "${missingItems[@]}" \
+		    || messagePrintf 'ERROR: Failed to add missing items in %s.\n' "$subject"
 
 		[ ! "$isPrintDefinitions" ] || printf '%s\n' "$subject"
 	    fi
@@ -1174,7 +1175,7 @@ addItems()
 	else
 	    printf >&2 'ERROR: Invalid type: %s\n' "$prefix"
 	    exit 3
-	fi
+	fi || return $?
 	addedItems["$item"]=t	# Record all added items for the config, decorate type / preinstall check.
     done
 }
@@ -1200,7 +1201,10 @@ hasOrAddItems()
     done
 
     [ ${#missingItems[@]} -eq 0 ] && return 1
-    addItems "${missingItems[@]}"
+    if ! addItems "${missingItems[@]}"; then
+	messagePrintf 'ERROR: Failed to add missing items in %s.\n' "$(getSubjectFromItems "${missingItems[@]}")"
+	return 1
+    fi
 }
 
 
