BUG: Need to re-enable normal shell globbing behavior when executing install commands
The python3-charset-normalizer workaround to duplicate dist-info/METADATA in order to suppress pip3 warning doesn't work because there's no globbing.
The postinstall:custom: is translated into a setup-software --execute --post --action command-line that has preserved the filespec globs so far. Now is the time to expand them, but setup-software's default disabling of globbing prevents this and instead causes the postaction to fail.
> ln: failed to access '/usr/lib/python3.*/dist-packages/charset_normalizer-*-dist-info': No such file or directory
The --execute should behave like --print, or capturing and executing in a temp file; i.e. with default shell globbing.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -1532,8 +1532,9 @@ printInstallCommands()
 
     if [ "$isExecute" ]; then
 	local installCommandline="$(joinBy '; ' "${toBeInstalledCommands[@]}")"
-	set -e
-	eval "$installCommandline" || exit $?	# Exit the script now because else installation failure would be treated as if there were no installation commands.
+	set -e +o noglob; shopt -qu nullglob
+	    eval "$installCommandline" || exit $?	# Exit the script now because else installation failure would be treated as if there were no installation commands.
+	set +e -o noglob; shopt -qs nullglob
     elif [ ! "$isPrintDefinitions" ] || [ "$isPrint" ]; then
 	printf '%s\n' "${toBeInstalledCommands[@]}"
     fi
