Refactoring: Move error message from getInstalled*() to has*()
This way, we can include the current item in the error, which gives more information to the user what got skipped. It also make the error message less repetitive (once per item of a failing type).

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -201,17 +201,16 @@ getInstalledNativePackages()
 	installedNativePackages["$package"]=t
 	case ",${DEBUG:-}," in *,setup-software:native,*) echo >&2 "${PS4}setup-software (native): Found $package";; esac
     done < <(dpkg-package-list; printf %d "$?")
-    if [ $exitStatus -ne 0 -o ${#installedNativePackages[@]} -eq 0 ]; then
-	echo >&2 'ERROR: Failed to obtain installed native package list.'
-	return 1
-    fi
-
-    isInstalledNativePackagesAvailable=t
+    [ $exitStatus -eq 0 -a ${#installedNativePackages[@]} -gt 0 ] && isInstalledNativePackagesAvailable=t
 }
 typeset -A addedNativePackages=()
 hasNative()
 {
-    getInstalledNativePackages || return 99
+    if ! getInstalledNativePackages; then
+	echo >&2 "ERROR: Failed to obtain installed native package list; skipping ${1}."
+	return 99
+    fi
+
     [ "${addedNativePackages["${1:?}"]}" ] || [ "${installedNativePackages["${1:?}"]}" ]
 }
 addNative()
