Support multiple definition group filters on a single line
Doing similar parsing as for the definitions (just skipping the extraction of a potential trailing comment; there's no use for that).
Add some more error handling as now definition group filters could be mixed with ordinary items; lastDefinitionGroupFilterItem serves both as a flag whether we've already seen one and stores the name for a better error message.

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -823,17 +823,27 @@ do
 	[[ "$line" =~ ^[[:space:]]*# ]] && continue
 	[[ "$line" =~ ^[[:space:]]*$ ]] && continue
 
-	eval "evaluatedLine=$line"
-	filter="${evaluatedLine#*:}"
-	prefix="${evaluatedLine%"$filter"}"
-	if contains "$prefix" "${!definitionGroupFilterTypeRegistry[@]}"; then
-	    definitionGroupFilterFunction="${definitionGroupFilterTypeRegistry["$prefix"]}"
-	    if [ -n "$definitionGroupFilterFunction" ]; then
-		eval "isDefinitionGroupAcceptedBy${definitionGroupFilterFunction} \"\$filter\" \"group \$definitionGroupFile\"" || \
-		    continue 2	# Skip the entire definiton group file.
+	eval "set -- ${line%%[	 ]#*}"
+	lastDefinitionGroupFilterItem=
+	for item
+	do
+	    filter="${item#*:}"
+	    prefix="${item%"$filter"}"
+	    if contains "$prefix" "${!definitionGroupFilterTypeRegistry[@]}"; then
+		lastDefinitionGroupFilterItem="$item"
+		definitionGroupFilterFunction="${definitionGroupFilterTypeRegistry["$prefix"]}"
+		if [ -n "$definitionGroupFilterFunction" ]; then
+		    eval "isDefinitionGroupAcceptedBy${definitionGroupFilterFunction} \"\$filter\" \"group \$definitionGroupFile\"" || \
+			continue 3	# Skip the entire definiton group file.
+		fi
+	    elif [ -n "$lastDefinitionGroupFilterItem" ]; then
+		printf >&2 'ERROR: Definition group filter types (%s) must not be mixed with other items (%s) in a single definition.\n' "$lastDefinitionGroupFilterItem" "$item"
+		exit 3
+	    else
+		break	# If the first item isn't a definition group filter, the other's cannot be such, neither. We'll catch any in the later processing stages.
 	    fi
-	    continue	# Just skip this filter definition.
-	fi
+	done
+	[ -n "$lastDefinitionGroupFilterItem" ] && continue
 
 	if [ ${#selections[@]} -eq 0 ]; then
 	    definitions+=("$line")
