ENH: Add wine+url item type

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -56,7 +56,7 @@ triplet / quadruplet.
 If ~/install/(SUBDIR|*)/(NAME|*)/PACKAGE-GLOB already exists [and if it is
 younger than MAX-AGE[SUFFIX]], it will be used; else, the *.deb from URL will
 be downloaded (and put into ~/install/* if it exists). If no URL is given and
-the pacakge does not exist, the installation will fail.
+the package does not exist, the installation will fail.
 HELPTEXT
 	    printf "$padding"
 	    ;;&
@@ -73,6 +73,20 @@ HELPTEXT
 	    ;;&
 	''|npm)	cat <<'HELPTEXT'
 npm: items refer to the Node.js package (or "Node modules") installer.
+HELPTEXT
+	    printf "$padding"
+	    ;;&
+	''|wine+url)	cat <<'HELPTEXT'
+wine+url: items consist of a
+    EXECUTABLE-NAME?:[:MAX-AGE[SUFFIX]]:[[SUBDIR/]NAME/]PACKAGE-GLOB:[URL]
+triplet / quadruplet.
+If EXECUTABLE-NAME? (located in Wine's drive C: unless it's an absolute path)
+exists / resolves to an existing file or directory, the item is deemed already
+installed.
+Else if ~/install/(SUBDIR|*)/(NAME|*)/PACKAGE-GLOB already exists [and if it is
+younger than MAX-AGE[SUFFIX]], it will be used; else, the *.exe / *.msi from URL
+will be downloaded (and put into ~/install/* if it exists). If no URL is given
+and the package does not exist, the installation will fail.
 HELPTEXT
 	    printf "$padding"
 	    ;;&
@@ -250,6 +264,21 @@ getInstalledNpmPackages()
     isInstalledNpmPackagesAvailable=t
 }
 
+hasWinePackage()
+{
+    if [[ ! "$1" =~ ^[^:]+\?:.+:. ]]; then
+	printf >&2 'ERROR: Invalid wine+url item: "wine+url:%s"\n' "$1"
+	exit 3
+    fi
+    local checkGlob="${1%%:*}"
+
+    local -r wineDriveC=~/.wine/drive_c
+    if [[ ! "$checkGlob" =~ ^/ ]] && [ -d "$wineDriveC" ]; then
+	which "${wineDriveC}/${checkGlob%\?}" >/dev/null 2>&1 || expandglob -- "${wineDriveC}/${checkGlob%\?}" >/dev/null 2>&1 && return 0
+    fi
+    which "${checkGlob%\?}" >/dev/null 2>&1 || expandglob -- "${checkGlob%\?}" >/dev/null 2>&1
+}
+
 customCheck()
 {
     local customAction="${1#*:}"
@@ -293,6 +322,7 @@ hasItem()
 	snap:)		! getInstalledSnapPackages		|| [ "${installedSnapPackages["$name"]}" ];;
 	pip3:)		! getInstalledPip3Packages		|| [ "${installedPip3Packages["$name"]}" ];;
 	npm:)		! getInstalledNpmPackages		|| [ "${installedNpmPackages["$name"]}" ];;
+	wine+url:)	hasWinePackage "$name";;
 	custom:)	customCheck "$name";;
 	*)		printf >&2 'ERROR: Invalid type: %s\n' "$prefix"; exit 3;;
     esac
@@ -310,6 +340,7 @@ typeset -a addedDebUrlPackages=()
 typeset -a addedSnapPackages=()
 typeset -a addedPip3Packages=()
 typeset -a addedNpmPackages=()
+typeset -a addedWineUrlPackages=()
 typeset -a addedCustomActions=()
 typeset -a addedPostinstallArgs=()
 hasDebSrc()
@@ -353,6 +384,7 @@ addItems()
 	    snap:)	    isAvailable snap snapd && addedSnapPackages+=("$name");;
 	    pip3:)	    isAvailable pip3 && addedPip3Packages+=("$name");;
 	    npm:)	    isAvailable npm  && addedNpmPackages+=("$name");;
+	    wine+url:)	    isAvailable wine && addedWineUrlPackages+=("$name");;
 	    custom:)	    addedCustomActions+=("${name#*:}");;
 	    postinstall:)   # Convert the "postinstall:ACTION\nITEM" to
 			    # --check "$ITEM" --action "$ACTION".
@@ -434,6 +466,29 @@ npmInstall()
     [ ${#addedNpmPackages[@]} -gt 0 ] || return
     local IFS=' '
     toBeInstalledCommands+=("${SUDO}${SUDO:+ }npm install --global ${addedNpmPackages[*]}")
+}
+
+wineUrlInstall()
+{
+    [ ${#addedWineUrlPackages[@]} -gt 0 ] || return
+    local wineUrlRecord; for wineUrlRecord in "${addedWineUrlPackages[@]}"
+    do
+	local maxAge=
+	local packageNameGlobUrl="${wineUrlRecord#*:}"
+	if [[ "$packageNameGlobUrl" =~ ^[0-9]+([smhdwyg]|mo): ]]; then
+	    maxAge="${BASH_REMATCH[0]%:}"
+	    packageNameGlobUrl="${packageNameGlobUrl#"${BASH_REMATCH[0]}"}"
+	fi
+	local packageUrl="${packageNameGlobUrl#*:}"
+	local packageNameAndGlob="${packageNameGlobUrl%:$packageUrl}"
+	local packageGlob="${packageNameAndGlob##*/}"
+	local packageName="${packageNameAndGlob%"$packageGlob"}"
+	packageName="${packageName%/}"
+
+	# Note: No sudo here, as downloading and installation will happen as the
+	# current user.
+	toBeInstalledCommands+=("wine-download-installer${packageName:+ --application-name "'"}${packageName}${packageName:+"'"} --expression '$packageGlob'${maxAge:+ --max-age }$maxAge --url '$packageUrl'")
+    done
 }
 
 customInstall()
@@ -624,6 +679,7 @@ debUrlInstall
 snapInstall
 pip3Install
 npmInstall
+wineUrlInstall
 customInstall
 postInstall
 
