ENH: Allow require: items that can refer to another ITEM, using the new isAvailable<TYPE>() functions

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -72,6 +72,9 @@ printConfigUsageForTypes()
 	if [ -n "$typeFunction" ]; then
 	    printf "$padding"; padding=$'\n'
 	    eval "configUsage${typeFunction}"
+	elif [ "$prefix" = require ]; then
+	    printf "$padding"; padding=$'\n'
+	    configUsageRequire
 	elif [ "$prefix" = preinstall ]; then
 	    printf "$padding"; padding=$'\n'
 	    configUsagePreinstall
@@ -116,6 +119,8 @@ HELPTEXT
 
 	printConfigUsageForTypes "${prefixes[@]%:}"    # Show config help for all types (in the order in which the types are also installed).
 
+	echo
+	configUsageRequire
 	echo
 	configUsagePreinstall
 	echo
@@ -188,6 +193,17 @@ configUsageNative()
     cat <<'HELPTEXT'
 Items without a prefix refer to packages installed via the distribution's
 package manager (apt).
+HELPTEXT
+}
+configUsageRequire()
+{
+    cat <<'HELPTEXT'
+require: items consist of a CHECK that can be:
+- another ITEM (in abbreviated form, usually just having one "package name"
+  parameter); for packages installed via the distribution's package manager, use
+  the special "native:" prefix here. The check passes if that ITEM has already
+  been installed or has already been selected by the user in the current
+  session.
 HELPTEXT
 }
 configUsagePreinstall()
@@ -568,6 +584,33 @@ do
     eval "set -- $items"
     itemVerb=are; [ -n "$comment" -o $# -eq 1 ] && itemVerb=is
     itemAuxVerb=
+
+    for item
+    do
+	case "$item" in
+	    require:*)
+		requirement="${item#require:}"
+		name="${requirement#*:}"
+		prefix="${requirement%"$name"}"
+		typeFunction="${typeRegistry["${prefix:-native:}"]}"
+		if [ -n "$typeFunction" ]; then
+		    availabilityFunctionName="isAvailable${typeFunction}"
+		    if type -t "$availabilityFunctionName" >/dev/null; then
+			if ! eval "$availabilityFunctionName \"\$name\""; then
+			    [ "$isVerbose" ] && printf >&2 'Skipping because requirement %s is not passed: %s\n' "$requirement" "$definition"
+			    continue 2
+			fi
+		    else
+			printf >&2 'ERROR: Type %s cannot be used for requirements checking.\n' "${prefix:-native}"
+			exit 3
+		    fi
+		elif [[ "$prefix" =~ ^[^[:space:]]+$ ]]; then
+		    printf >&2 'ERROR: Invalid type: %s\n' "$prefix"
+		    exit 3
+		fi
+		;;
+	esac
+    done
 
     typeset -a missingItems=()
     lastMissingItem=
