Refactoring: Split and distribute the config usages, too

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -62,9 +62,26 @@ HELPDESCRIPTION
 HELPTEXT
 }
 
+
+printConfigUsageForTypes()
+{
+    local padding=
+    local prefix; for prefix
+    do
+	local typeFunction="${typeRegistry["${prefix:-native}:"]}"
+	if [ -n "$typeFunction" ]; then
+	    printf "$padding"; padding=$'\n'
+	    eval "configUsage${typeFunction}"
+	else
+	    printf >&2 'ERROR: Invalid type: %s\n' "$prefix"
+	    exit 3
+	fi
+    done
+}
 printConfigUsage()
 {
-    cat <<'HELPTEXT'
+    if [ $# -eq 0 ]; then
+	cat <<'HELPTEXT'
 A definition consists of one or many whitespace-separated ITEMs, optionally
 followed by a # DESCRIPTION. It can be broken over multiple lines, with a
 trailing \ as the line continuation character.
@@ -72,139 +89,17 @@ Definitions are grouped into DEFINITION-GROUPs which contain definitions that
 belong to a certain category or are typically installed together for a certain
 use case.
 HELPTEXT
-    echo
-    local padding=
-    case "$1" in
-	'') cat <<'HELPTEXT'
-Items without a prefix refer to packages installed via the distribution's
-package manager (apt).
-HELPTEXT
-	    padding='\n'
-	    ;;&
-	''|ppa)	cat <<'HELPTEXT'
-ppa: items refer to Ubuntu personal package archives that enable additional
-packages (or other versions) to be installed through apt.
-HELPTEXT
-	    printf "$padding"
-	    ;;&
-	''|deb-build) cat <<'HELPTEXT'
-deb-build: items refer to packages that satisfy the build dependencies for a
-source package.
-HELPTEXT
-	    printf "$padding"
-	    ;;&
-	''|deb+url) cat <<'HELPTEXT'
-deb+url: items consist of a
-    PACKAGE[:MAX-AGE[SUFFIX]]:[[SUBDIR/]NAME/]PACKAGE-GLOB:[URL]
-triplet / quadruplet.
-If ~/install/(SUBDIR|*)/(NAME|*)/PACKAGE-GLOB already exists [and if it is
-younger than MAX-AGE[SUFFIX]], it will be used; else, the *.deb from URL will
-be downloaded (and put into ~/install/* if it exists). If no URL is given and
-the package does not exist, the installation will fail.
-HELPTEXT
-	    printf "$padding"
-	    ;;&
-	''|snap) cat <<'HELPTEXT'
-snap: items refer to packages from the Snap store that work across many
-different Linux distributions, are segregated and update automatically.
-HELPTEXT
-	    printf "$padding"
-	    ;;&
-	''|pip3)    cat <<'HELPTEXT'
-pip3: items refer to the Python package installer.
-HELPTEXT
-	    printf "$padding"
-	    ;;&
-	''|npm)	cat <<'HELPTEXT'
-npm: items refer to the Node.js package (or "Node modules") installer.
-HELPTEXT
-	    printf "$padding"
-	    ;;&
-	''|wine+url)	cat <<'HELPTEXT'
-wine+url: items consist of a
-    EXECUTABLE-NAME?[:MAX-AGE[SUFFIX]]:[[SUBDIR/]NAME/]PACKAGE-GLOB:[URL]
-triplet / quadruplet.
-If EXECUTABLE-NAME? (located in Wine's drive C: unless it's an absolute path)
-exists / resolves to an existing file or directory, the item is deemed already
-installed.
-Else if ~/install/(SUBDIR|*)/(NAME|*)/PACKAGE-GLOB already exists [and if it is
-younger than MAX-AGE[SUFFIX]], it will be used; else, the *.exe / *.msi from URL
-will be downloaded (and put into ~/install/* if it exists). If no URL is given
-and the package does not exist, the installation will fail.
-HELPTEXT
-	    printf "$padding"
-	    ;;&
-	''|custom)  cat <<'HELPTEXT'
-custom: items consist of a CHECK:ACTION pair.
-CHECK can be one of the following (in decreasing precedence):
-- an EXECUTABLE-COMMAND in the ./etc/custom directory tree that is called and
-  should succeed if the application already exists, and fail if it is missing;
-  if EXECUTABLE-COMMAND starts with a &, this is replaced by the following
-  ACTION (without a $SUDO prefix), allowing you to save repeated typing:
-	custom:&-check:foo-installer
-- an EXECUTABLE-NAME? (located through $PATH) or GLOB?, and succeeds if
-  it's there / resolves to an existing file or directory
-- the special expression "false"; then, no check is performed and whether the
-  installation action will happen depends solely on the (potentially recalled or
-  derived from the whole definition) user's answer
-- a TEST-EXPRESSION (whitespace must be escaped or the entire expression
-  quoted!) that is eval'd and should succeed if the application already
-  exists, and fail if it is missing; if TEST-EXPRESSION starts with a &, this
-  is replaced by the following ACTION (without a $SUDO prefix), allowing you
-  to re-use the same script for checking and installing:
-	custom:'& --check':foo-installer
-    or save repeated typing:
-	custom:&-check:foo-installer
-ACTION is one of the following:
-- an executable command in the ./etc/custom directory tree that is invoked
-  (prepend $SUDO if it needs to be invoked as root) and should then install
-  the application
-- a text file in the ./etc/custom directory tree whose file name (without
-  extension) is taken as a notification title and contents as notification to be
-  displayed (presumably with instructions for manual installation steps)
-  immediately and on each login until the user acknowledges it
-- an INSTALL-EXPRESSION (whitespace must be escaped or the entire expression
-  quoted!) that is eval'd (prepend $SUDO if it needs to be invoked as root)
-HELPTEXT
-	    printf "$padding"
-	    ;;&
-	''|preinstall)	cat <<'HELPTEXT'
-preinstall: items consist of an ACTION that is one of the following:
-- an executable command in the ./etc/preinstall directory tree that is invoked
-  (prepend $SUDO if it needs to be invoked as root) and should then perform the
-  preinstallation steps
-- a text file in the ./etc/preinstall directory tree whose file name (without
-  extension) is taken as a notification title and contents as notification to be
-  displayed (presumably with instructions for manual pre-installation steps)
-  immediately and on each login until the user acknowledges it
-- another ITEM (that is then executed as usual); for packages installed via the
-  distribution's package manager, use the special "native:" prefix here
-- a PREINSTALL-EXPRESSION (whitespace must be escaped or the entire expression
-  quoted!) that is eval'd (prepend $SUDO if it needs to be invoked as root)
-A preinstall item runs (before other installation actions) if the
-non-pre/postinstall item preceding it in the current definition is missing, but
-the definition has now been selected.
-HELPTEXT
-	    ;;&
-	''|postinstall)	cat <<'HELPTEXT'
-postinstall: items consist of an ACTION that is one of the following:
-- an executable command in the ./etc/postinstall directory tree that is invoked
-  (prepend $SUDO if it needs to be invoked as root) and should then perform the
-  postinstallation steps
-- a text file in the ./etc/postinstall directory tree whose file name (without
-  extension) is taken as a notification title and contents as notification to be
-  displayed (presumably with instructions for manual post-installation steps)
-  immediately and on each login until the user acknowledges it
-- another ITEM (that is then executed as usual); for packages installed via the
-  distribution's package manager, use the special "native:" prefix here
-- a POSTINSTALL-EXPRESSION (whitespace must be escaped or the entire expression
-  quoted!) that is eval'd (prepend $SUDO if it needs to be invoked as root)
-A postinstall item runs if the non-pre/postinstall item preceding it in the
-current definition was missing, but has been successfully installed by the
-installation commands.
-HELPTEXT
-	    ;;&
-    esac
+	echo
+	typeset -a prefixes=("${!typeRegistry[@]}")
+	printConfigUsageForTypes "${prefixes[@]%:}"    # Show config help for all types (for simplicity in undefined order).
+
+	echo
+	configUsagePreinstall
+	echo
+	configUsagePostinstall
+    else
+	printConfigUsageForTypes "$@"
+    fi
 }
 
 typeset -A typeRegistry=([native:]=Native)
@@ -259,6 +154,54 @@ hasNative()
 addNative()
 {
     addedNativePackages+=("${1:?}")
+}
+
+configUsageNative()
+{
+    cat <<'HELPTEXT'
+Items without a prefix refer to packages installed via the distribution's
+package manager (apt).
+HELPTEXT
+}
+configUsagePreinstall()
+{
+    cat <<'HELPTEXT'
+preinstall: items consist of an ACTION that is one of the following:
+- an executable command in the ./etc/preinstall directory tree that is invoked
+  (prepend $SUDO if it needs to be invoked as root) and should then perform the
+  preinstallation steps
+- a text file in the ./etc/preinstall directory tree whose file name (without
+  extension) is taken as a notification title and contents as notification to be
+  displayed (presumably with instructions for manual pre-installation steps)
+  immediately and on each login until the user acknowledges it
+- another ITEM (that is then executed as usual); for packages installed via the
+  distribution's package manager, use the special "native:" prefix here
+- a PREINSTALL-EXPRESSION (whitespace must be escaped or the entire expression
+  quoted!) that is eval'd (prepend $SUDO if it needs to be invoked as root)
+A preinstall item runs (before other installation actions) if the
+non-pre/postinstall item preceding it in the current definition is missing, but
+the definition has now been selected.
+HELPTEXT
+}
+configUsagePostinstall()
+{
+    cat <<'HELPTEXT'
+postinstall: items consist of an ACTION that is one of the following:
+- an executable command in the ./etc/postinstall directory tree that is invoked
+  (prepend $SUDO if it needs to be invoked as root) and should then perform the
+  postinstallation steps
+- a text file in the ./etc/postinstall directory tree whose file name (without
+  extension) is taken as a notification title and contents as notification to be
+  displayed (presumably with instructions for manual post-installation steps)
+  immediately and on each login until the user acknowledges it
+- another ITEM (that is then executed as usual); for packages installed via the
+  distribution's package manager, use the special "native:" prefix here
+- a POSTINSTALL-EXPRESSION (whitespace must be escaped or the entire expression
+  quoted!) that is eval'd (prepend $SUDO if it needs to be invoked as root)
+A postinstall item runs if the non-pre/postinstall item preceding it in the
+current definition was missing, but has been successfully installed by the
+installation commands.
+HELPTEXT
 }
 
 addPreinstall()
