ENH: Implement postinstall-or-once: type variant of postinstall:
This allows to also run the action if the previous item is preinstalled (like Firefox or Thunderbird).

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -89,6 +89,9 @@ printConfigUsageForTypes()
 	elif [ "$prefix" = postinstall ]; then
 	    printf "$padding"; padding=$'\n'
 	    configUsagePostinstall
+	elif [ "$prefix" = postinstall-or-once ]; then
+	    printf "$padding"; padding=$'\n'
+	    configUsagePostinstall
 	else
 	    printf >&2 'ERROR: Invalid type: %s\n' "$prefix"
 	    exit 3
@@ -243,6 +246,30 @@ current definition was missing, but has been successfully installed by the
 installation commands.
 HELPTEXT
 }
+configUsagePostinstallOrOnce()
+{
+    cat <<'HELPTEXT'
+postinstall-or-once: items consist of [ID:]ACTION where the latter is one of the
+following:
+- an executable command (potentially followed by command-line arguments) in the
+  ./etc/postinstall directory tree that is invoked (prepend $SUDO if it needs to
+  be invoked as root) and should then perform the postinstallation steps
+- a text file in the ./etc/postinstall directory tree whose file name (without
+  extension) is taken as a notification title and contents as notification to be
+  displayed (presumably with instructions for manual post-installation steps)
+  immediately and on each login until the user acknowledges it
+- another ITEM (that is then executed as usual); for packages installed via the
+  distribution's package manager, use the special "native:" prefix here
+- a POSTINSTALL-EXPRESSION (whitespace must be escaped or the entire expression
+  quoted!) that is eval'd (prepend $SUDO if it needs to be invoked as root)
+Like a postinstall item, a postinstall-or-once item runs if the
+non-pre/postinstall item preceding it in the current definition was missing, but
+has been successfully installed by the installation commands. Additionally, if
+the non-pre/postinstall item preceding it already existed (e.g. it comes
+preinstalled), it will also run once; ID or ACTION itself is used for that
+uniqueness check.
+HELPTEXT
+}
 
 addPreinstall()
 {
@@ -355,8 +382,8 @@ hasOrAddItems()
     do
 	local name="${item#*:}"
 	local prefix="${item%"$name"}"
-	if contains "$prefix" "${!definitionFilterTypeRegistry[@]}" preinstall: postinstall:; then
-	    printf >&2 'ERROR: Cannot use a %s type within a preinstall / postinstall item.\n' "$prefix"
+	if contains "$prefix" "${!definitionFilterTypeRegistry[@]}" preinstall: postinstall: postinstall-or-once:; then
+	    printf >&2 'ERROR: Cannot use a %s type within a preinstall / postinstall[-or-once] item.\n' "$prefix"
 	    exit 3
 	fi
 
@@ -652,6 +679,23 @@ do
 		# installation of the previous item was successful. To be
 		# able to check that, we need that item as well, so append
 		# it on a new line.
+		missingItems+=("$item"$'\n'"$lastMissingItem")
+	    fi
+	elif [ "$prefix" = postinstall-or-once: ]; then
+	    if [ -z "$lastRealItem" ]; then
+		printf >&2 'ERROR: No previous item before %s.\n' "$item"
+		exit 3
+	    elif hasItem "$lastRealItem"; then
+		rest="${name#*:}"
+		id="${name%"$rest"}"; id="${id%:}"; id="${id:-$rest}"
+		if once --quiet --id "$id"; then
+		    # The item already is installed, but the check did not run yet.
+		    addPostinstall "$rest"$'\n'"$lastRealItem"
+		fi
+	    elif [ -n "$lastMissingItem" ]; then
+		# The postinstall action will run when the installation of the
+		# previous item was successful. To be able to check that, we
+		# need that item as well, so append it on a new line.
 		missingItems+=("$item"$'\n'"$lastMissingItem")
 	    fi
 	else
