Cosmetics: Move getDefinitionGroupFilespec() and testDefinitionGroupFilter() to the top
That mixture of code and functions is ugly and not worth the locality; it also prevents us from invoking some functions elsewhere.

diff --git a/bin/setup-software b/bin/setup-software
--- a/bin/setup-software
+++ b/bin/setup-software
@@ -191,6 +191,46 @@ do
 done
 set -o noglob
 
+getDefinitionGroupFilespec()
+{
+    local definitionGroupFile="${1:?}"; shift
+    local dirspec; for dirspec in "${definitionDirspecs[@]}"
+    do
+	local definitionGroupFilespec="${dirspec}/${definitionGroupFile}"
+	if [ -f "$definitionGroupFilespec" ]; then
+	    printf %s "$definitionGroupFilespec"
+	    return 0
+	fi
+    done
+    return 1
+}
+
+testDefinitionGroupFilter()
+{
+    local line="$1"; shift
+    eval "set -- ${line%%[	 ]#*}"
+    local lastDefinitionGroupFilterItem= item
+    for item
+    do
+	local filter="${item#*:}"
+	local prefix="${item%"$filter"}"
+	if contains "$prefix" "${!definitionGroupFilterTypeRegistry[@]}"; then
+	    lastDefinitionGroupFilterItem="$item"
+	    local definitionGroupFilterFunction="${definitionGroupFilterTypeRegistry["$prefix"]}"
+	    if [ -n "$definitionGroupFilterFunction" ]; then
+		eval "isDefinitionGroupAcceptedBy${definitionGroupFilterFunction} \"\$filter\" \"group \$definitionGroupFile, after line \$physicalLineCnt\"" || \
+		    return 2	# Skip the entire definition group file.
+	    fi
+	elif [ -n "$lastDefinitionGroupFilterItem" ]; then
+	    printf >&2 'ERROR: Definition group filter types (%s) must not be mixed with other items (%s) in a single definition.\n' "$lastDefinitionGroupFilterItem" "$item"
+	    exit 3
+	else
+	    return 0	# If the first item isn't a definition group filter, the other's cannot be such, neither. We'll catch any in the later processing stages.
+	fi
+    done
+    [ -n "$lastDefinitionGroupFilterItem" ] && return 1
+}
+
 isDefinitionGroupDir()
 {
     local group="${1:?}"; shift
@@ -784,46 +824,6 @@ elif [ $# -eq 0 ]; then
     printUsage "$0" >&2
     exit 2
 fi
-
-getDefinitionGroupFilespec()
-{
-    local definitionGroupFile="${1:?}"; shift
-    local dirspec; for dirspec in "${definitionDirspecs[@]}"
-    do
-	local definitionGroupFilespec="${dirspec}/${definitionGroupFile}"
-	if [ -f "$definitionGroupFilespec" ]; then
-	    printf %s "$definitionGroupFilespec"
-	    return 0
-	fi
-    done
-    return 1
-}
-
-testDefinitionGroupFilter()
-{
-    local line="$1"; shift
-    eval "set -- ${line%%[	 ]#*}"
-    local lastDefinitionGroupFilterItem= item
-    for item
-    do
-	local filter="${item#*:}"
-	local prefix="${item%"$filter"}"
-	if contains "$prefix" "${!definitionGroupFilterTypeRegistry[@]}"; then
-	    lastDefinitionGroupFilterItem="$item"
-	    local definitionGroupFilterFunction="${definitionGroupFilterTypeRegistry["$prefix"]}"
-	    if [ -n "$definitionGroupFilterFunction" ]; then
-		eval "isDefinitionGroupAcceptedBy${definitionGroupFilterFunction} \"\$filter\" \"group \$definitionGroupFile, after line \$physicalLineCnt\"" || \
-		    return 2	# Skip the entire definition group file.
-	    fi
-	elif [ -n "$lastDefinitionGroupFilterItem" ]; then
-	    printf >&2 'ERROR: Definition group filter types (%s) must not be mixed with other items (%s) in a single definition.\n' "$lastDefinitionGroupFilterItem" "$item"
-	    exit 3
-	else
-	    return 0	# If the first item isn't a definition group filter, the other's cannot be such, neither. We'll catch any in the later processing stages.
-	fi
-    done
-    [ -n "$lastDefinitionGroupFilterItem" ] && return 1
-}
 
 IFS=' '
 typeset -ra definitionGroups=("$@")
