Bash: Handle when we're used during PATH bootstrapping

diff --git a/etc/require/Bash b/etc/require/Bash
--- a/etc/require/Bash
+++ b/etc/require/Bash
@@ -1,4 +1,11 @@
 #!/bin/bash
 
+# For when we're used during PATH bootstrapping.
+if ! type -t versionRequirement >/dev/null; then
+    readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+    [ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+    PATH="${scriptDir}/../../../shell-packages/bin"
+fi
+
 VERSIONREQUIREMENT_BASE_VERSION="${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}.${BASH_VERSINFO[2]}.${BASH_VERSINFO[3]}" \
     exec versionRequirement "$@"
