{Redhat,Ubuntu}: Robustness: Parse integers only and complain when something else is passed

diff --git a/etc/require/Redhat b/etc/require/Redhat
--- a/etc/require/Redhat
+++ b/etc/require/Redhat
@@ -27,17 +27,20 @@ for versionRequirement
 do
     versionRequirement="${versionRequirement//./}"
     case "$versionRequirement" in
-	-*)	[ $redhatVersion -le ${versionRequirement#-} ] && exit 0;;
-	*+)	[ $redhatVersion -ge ${versionRequirement%+} ] && exit 0;;
-	*-*)	minVersion=${versionRequirement%-*}
-		maxVersion=${versionRequirement#*-}
-		[ $redhatVersion -ge $minVersion -a $redhatVersion -le $maxVersion ] && exit 0
-		;;
-	*%*)	minVersion=${versionRequirement%\%*}
-		maxVersion=${versionRequirement#*%}
-		[ $redhatVersion -lt $minVersion -o $redhatVersion -gt $maxVersion ] && exit 0
-		;;
-	*)	[ $redhatVersion -eq $versionRequirement ] && exit 0;;
+	-+([0-9]))	    [ $redhatVersion -le ${versionRequirement#-} ] && exit 0;;
+	+([0-9])+)	    [ $redhatVersion -ge ${versionRequirement%+} ] && exit 0;;
+	+([0-9])-+([0-9]))  minVersion=${versionRequirement%-*}
+			    maxVersion=${versionRequirement#*-}
+			    [ $redhatVersion -ge $minVersion -a $redhatVersion -le $maxVersion ] && exit 0
+			    ;;
+	+([0-9])%+([0-9]))  minVersion=${versionRequirement%\%*}
+			    maxVersion=${versionRequirement#*%}
+			    [ $redhatVersion -lt $minVersion -o $redhatVersion -gt $maxVersion ] && exit 0
+			    ;;
+	+([0-9]))	    [ $redhatVersion -eq $versionRequirement ] && exit 0;;
+	*)		    printf >&2 'ERROR: Invalid version requirement: %s\n' "$versionRequirement"
+			    exit 2
+			    ;;
     esac
 done
 exit 1
diff --git a/etc/require/Ubuntu b/etc/require/Ubuntu
--- a/etc/require/Ubuntu
+++ b/etc/require/Ubuntu
@@ -1,4 +1,5 @@
 #!/bin/bash
+shopt -qs extglob
 
 printUsage()
 {
@@ -21,17 +22,20 @@ for versionRequirement
 do
     versionRequirement="${versionRequirement//./}"
     case "$versionRequirement" in
-	-*)	[ $ubuntuVersion -le ${versionRequirement#-} ] && exit 0;;
-	*+)	[ $ubuntuVersion -ge ${versionRequirement%+} ] && exit 0;;
-	*-*)	minVersion=${versionRequirement%-*}
-		maxVersion=${versionRequirement#*-}
-		[ $ubuntuVersion -ge $minVersion -a $ubuntuVersion -le $maxVersion ] && exit 0
-		;;
-	*%*)	minVersion=${versionRequirement%\%*}
-		maxVersion=${versionRequirement#*%}
-		[ $ubuntuVersion -lt $minVersion -o $ubuntuVersion -gt $maxVersion ] && exit 0
-		;;
-	*)	[ $ubuntuVersion -eq $versionRequirement ] && exit 0;;
+	-+([0-9]))	    [ $ubuntuVersion -le ${versionRequirement#-} ] && exit 0;;
+	+([0-9])+)	    [ $ubuntuVersion -ge ${versionRequirement%+} ] && exit 0;;
+	+([0-9])-+([0-9]))  minVersion=${versionRequirement%-*}
+			    maxVersion=${versionRequirement#*-}
+			    [ $ubuntuVersion -ge $minVersion -a $ubuntuVersion -le $maxVersion ] && exit 0
+			    ;;
+	+([0-9])%+([0-9]))  minVersion=${versionRequirement%\%*}
+			    maxVersion=${versionRequirement#*%}
+			    [ $ubuntuVersion -lt $minVersion -o $ubuntuVersion -gt $maxVersion ] && exit 0
+			    ;;
+	+([0-9]))	    [ $ubuntuVersion -eq $versionRequirement ] && exit 0;;
+	*)		    printf >&2 'ERROR: Invalid version requirement: %s\n' "$versionRequirement"
+			    exit 2
+			    ;;
     esac
 done
 exit 1
